name: CI - Build and Update GitOps

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      build_backend:
        description: "Force build backend"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

      build_frontend:
        description: "Force build frontend"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
env:
  PROJECT_ID: project-40d105bf-bb2b-4bf6-b9f
  REGION: us-east5
  REPOSITORY: gcp-three-tier
  GITOPS_REPO: https://github.com/ashequrrasul/gke-three-tier-gitops.git
  GITOPS_BRANCH: main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  build-backend:
    needs: detect-changes
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.build_backend == 'true' ||
      github.event_name == 'push' && needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOYER_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build backend image
        run: |
          BACKEND_IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/backend:${{ github.sha }}
          docker build -t $BACKEND_IMAGE ./backend
          docker push $BACKEND_IMAGE
          echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV

      - name: Update backend image in GitOps repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/ashequrrasul/gke-three-tier-gitops.git gitops
          cd gitops

           yq -i '.backend.image.tag = "${{ github.sha }}"' charts/three-tier-app/values.yaml

          git add charts/three-tier-app/values.yaml
          git commit -m "Update backend image to ${{ github.sha }}" || echo "No backend image change"
          git push origin main
      - name: Render Helm manifests
        run: |
          mkdir -p rendered
          helm template gke-three-tier-helm-app gitops/charts/three-tier-app \
            -n three-tier-helm > rendered/three-tier-app-${{ github.sha }}.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests-${{ github.sha }}
          path: rendered/

  build-frontend:
    needs: detect-changes
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.build_frontend == 'true' ||
      github.event_name == 'push' && needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOYER_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build frontend image
        run: |
          FRONTEND_IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/frontend:${{ github.sha }}
          docker build -t $FRONTEND_IMAGE ./frontend
          docker push $FRONTEND_IMAGE
          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV

      - name: Update frontend image in GitOps repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/ashequrrasul/gke-three-tier-gitops.git gitops
          cd gitops

          yq -i '.frontend.image.tag = "${{ github.sha }}"' charts/three-tier-app/values.yaml

          git add charts/three-tier-app/values.yaml
          git commit -m "Update frontend image to ${{ github.sha }}" || echo "No frontend image change"
          git push origin main
      - name: Render Helm manifests
        run: |
          mkdir -p rendered
          helm template gke-three-tier-helm-app gitops/charts/three-tier-app \
            -n three-tier-helm > rendered/three-tier-app-${{ github.sha }}.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests-${{ github.sha }}
          path: rendered/